name: mobile_shop_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.8
  flutter_secure_storage: ^8.0.0
  flutter_dotenv: ^5.1.0
  quickalert: ^1.1.0
  dots_indicator: ^3.0.0
  carousel_slider: ^5.0.0
  image_sequence_animator: ^2.0.0
  flutter_rating_stars: ^1.1.0
  flutter_rating_bar: ^4.0.1
  intl: ^0.19.0
  awesome_drawer_bar: ^1.2.0
  provider: ^6.1.2
  animation_search_bar: ^0.0.10
  sqflite: ^2.3.3+1
  path: ^1.9.0
  path_provider: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo_icon/
    - assets/.env
