name: mobile_shop_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  salomon_bottom_bar: ^3.3.2
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  image_sequence_animator: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/logo_icon/
    - assets/guitarSequence/
