// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCoMmWZHFB2Y9SyAgeu5Jqw0jhmidRVfUg',
    appId: '1:980222294977:android:1b842471b1bc6a0f1f8d40',
    messagingSenderId: '980222294977',
    projectId: 'mobileflutter-297db',
    storageBucket: 'mobileflutter-297db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9TfXnwB0W9mzF8KPfqJM5VDtnsoyEvpE',
    appId: '1:980222294977:ios:299334ca6b9ae5391f8d40',
    messagingSenderId: '980222294977',
    projectId: 'mobileflutter-297db',
    storageBucket: 'mobileflutter-297db.appspot.com',
    iosBundleId: 'com.example.mobileShopFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9TfXnwB0W9mzF8KPfqJM5VDtnsoyEvpE',
    appId: '1:980222294977:ios:299334ca6b9ae5391f8d40',
    messagingSenderId: '980222294977',
    projectId: 'mobileflutter-297db',
    storageBucket: 'mobileflutter-297db.appspot.com',
    iosBundleId: 'com.example.mobileShopFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAI3eBq2DKTjxdyxxLe0JKCeuthxMze55E',
    appId: '1:980222294977:web:249372b1da9205791f8d40',
    messagingSenderId: '980222294977',
    projectId: 'mobileflutter-297db',
    authDomain: 'mobileflutter-297db.firebaseapp.com',
    storageBucket: 'mobileflutter-297db.appspot.com',
    measurementId: 'G-M9Y9LH7YZH',
  );
}
